### ISSUE TITLE
tabular data/ noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [hrayrhar/limit-label-memorization#3]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by hrayrhar** [comment]
Hi @nazaretl,

1. Yes, it is applicable to tabular data, but I guess you would need to change the network architecture.

2. Yes, in the paper we demonstrated one way of identifying noisy examples -- you need to rank the examples by the norm of the difference between predicted and actual gradients. Please see the `examine_model` function in https://github.com/hrayrhar/limit-label-memorization/blob/master/notebooks/visualize-results.ipynb.

Hrayr

**Comment by nazaretl** [comment]
many thanks for the explanation!

Lusiné
